
// OLD
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_RESET = "CART_RESET";

// Add to Local Cart
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

// Remove from Local Cart
export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL";

// Add to User Cart on DB
export const ADD_TO_DB_CART_REQUEST = "ADD_TO_DB_CART_REQUEST";
export const ADD_TO_DB_CART_SUCCESS = "ADD_TO_DB_CART_SUCCESS";
export const ADD_TO_DB_CART_FAIL = "ADD_TO_DB_CART_FAIL";

// Remove from Local Cart
export const REMOVE_FROM_DB_CART_REQUEST = "REMOVE_FROM_DB_CART_REQUEST";
export const REMOVE_FROM_DB_CART_SUCCESS = "REMOVE_FROM_DB_CART_SUCCESS";
export const REMOVE_FROM_DB_CART_FAIL = "REMOVE_FROM_DB_CART_FAIL";

// Reset Cart
export const CART_RESET_REQUEST = "CART_RESET_REQUEST";
export const CART_RESET_SUCCESS = "CART_RESET_SUCCESS";
export const CART_RESET_FAIL = "CART_RESET_FAIL";