// ~~~~~~~~~~~~~~~~~~ User ~~~~~~~~~~~~~~~~~~

// User Login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

// User Logout
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

// User Registration
export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";

// Get User Address
export const GET_USER_ADDRESS_REQUEST = "GET_USER_ADDRESS_REQUEST";
export const GET_USER_ADDRESS_SUCCESS = "GET_USER_ADDRESS_SUCCESS";
export const GET_USER_ADDRESS_FAILURE = "GET_USER_ADDRESS_FAILURE";

// Reset Address
export const RESET_ADDRESS_REQUEST = "RESET_ADDRESS_REQUEST";
export const RESET_ADDRESS_SUCCESS = "RESET_ADDRESS_SUCCESS";
export const RESET_ADDRESS_FAILURE = "RESET_ADDRESS_FAILURE";

// Add User Address
export const ADD_USER_ADDRESS_REQUEST = "ADD_USER_ADDRESS_REQUEST";
export const ADD_USER_ADDRESS_SUCCESS = "ADD_USER_ADDRESS_SUCCESS";
export const ADD_USER_ADDRESS_FAILURE = "ADD_USER_ADDRESS_FAILURE";

// Add User Order
export const ADD_USER_ORDER_REQUEST = "ADD_USER_ORDER_REQUEST";
export const ADD_USER_ORDER_SUCCESS = "ADD_USER_ORDER_SUCCESS";
export const ADD_USER_ORDER_FAILURE = "ADD_USER_ORDER_FAILURE";

// Get User Orders
export const GET_USER_ORDER_REQUEST = "GET_USER_ORDER_REQUEST";
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS";
export const GET_USER_ORDER_FAILURE = "GET_USER_ORDER_FAILURE";

// Get Order Derails
export const GET_USER_ORDER_DETAILS_REQUEST = "GET_USER_ORDER_DETAILS_REQUEST";
export const GET_USER_ORDER_DETAILS_SUCCESS = "GET_USER_ORDER_DETAILS_SUCCESS";
export const GET_USER_ORDER_DETAILS_FAILURE = "GET_USER_ORDER_DETAILS_FAILURE";

