
// ~~~~~~~~~~~~~~~~~~ Admin User ~~~~~~~~~~~~~~~~~~

// Admin Login
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

// Admin Logout
export const ADMIN_LOGOUT_REQUEST = "ADMIN_LOGOUT_REQUEST";
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS";
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL";

// Admin Registration
export const ADMIN_REGISTRATION_REQUEST = "ADMIN_REGISTRATION_REQUEST";
export const ADMIN_REGISTRATION_SUCCESS = "ADMIN_REGISTRATION_SUCCESS";
export const ADMIN_REGISTRATION_FAIL = "ADMIN_REGISTRATION_FAIL";

// ~~~~~~~~~~~~~~~~~~ Categories ~~~~~~~~~~~~~~~~~~

// Get Categories
export const GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAIL = "GET_ALL_CATEGORIES_FAIL";

// Create Category
export const ADD_NEW_CATEGORY_REQUEST = "ADD_NEW_CATEGORY_REQUEST";
export const ADD_NEW_CATEGORY_SUCCESS = "ADD_NEW_CATEGORY_SUCCESS";
export const ADD_NEW_CATEGORY_FAIL = "ADD_NEW_CATEGORY_FAIL";

// Update Categories
export const UPDATE_CATEGORIES_REQUEST = "UPDATE_CATEGORIES_REQUEST";
export const UPDATE_CATEGORIES_SUCCESS = "UPDATE_CATEGORIES_SUCCESS";
export const UPDATE_CATEGORIES_FAIL = "UPDATE_CATEGORIES_FAIL";

// Delete Categories
export const DELETE_CATEGORIES_REQUEST = "DELETE_CATEGORIES_REQUEST";
export const DELETE_CATEGORIES_SUCCESS = "DELETE_CATEGORIES_SUCCESS";
export const DELETE_CATEGORIES_FAIL = "DELETE_CATEGORIES_FAIL";

// ~~~~~~~~~~~~~~~~~~ Products ~~~~~~~~~~~~~~~~~~

// Get Products
export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";

// Create Products
export const ADD_NEW_PRODUCT_REQUEST = "ADD_NEW_PRODUCT_REQUEST";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_FAIL = "ADD_NEW_PRODUCT_FAIL";

// ~~~~~~~~~~~~~~~~~~ Initial Data ~~~~~~~~~~~~~~~~~~

// Get Initial Data
export const GET_INITIAL_DATA_REQUEST = "GET_INITIAL_DATA_REQUEST";
export const GET_INITIAL_DATA_SUCCESS = "GET_INITIAL_DATA_SUCCESS";
export const GET_INITIAL_DATA_FAIL = "GET_INITIAL_DATA_FAIL";

// ~~~~~~~~~~~~~~~~~~ Get Orders ~~~~~~~~~~~~~~~~~~
export const GET_CUSTOMER_ORDERS_REQUEST = 'GET_CUSTOMER_ORDERS_REQUEST';
export const GET_CUSTOMER_ORDERS_SUCCESS = 'GET_CUSTOMER_ORDERS_SUCCESS';
export const GET_CUSTOMER_ORDERS_FAILURE = 'GET_CUSTOMER_ORDERS_FAILURE';

// ~~~~~~~~~~~~~~~~~~ Update Orders ~~~~~~~~~~~~~~~~~~
export const UPDATE_CUSTOMER_ORDER_REQUEST = 'UPDATE_CUSTOMER_ORDER_REQUEST';
export const UPDATE_CUSTOMER_ORDER_SUCCESS = 'UPDATE_CUSTOMER_ORDER_SUCCESS';
export const UPDATE_CUSTOMER_ORDER_FAILURE = 'UPDATE_CUSTOMER_ORDER_FAILURE';

